cibernox/ember-power-calendar

- package.json
> Make ember-moment and ember-moment-shim runtime dependencies

- tests/dummy/app/templates/public-pages/docs/how-to-use-it.hbs
The description of `selected` mentioned that the selected date was shown in a shade of grey. At least with the current styles, it's blue.
> Minor text tweak for docs mentioning color

- addon/templates/components/power-calendar/days.hbs
when including ember-power-calendar in a form selecting a day triggers form submission. added `<button type="button">` to override the default `type="submit"`
> added type='button' to days to not trigger form submit

- CHANGELOG.md
- addon/components/power-calendar.js
- addon/templates/components/power-calendar/nav.hbs
- tests/dummy/app/templates/components/calendar-nav-with-year-buttons.hbs
- tests/dummy/app/templates/snippets/the-nav-2.hbs
- tests/integration/components/power-calendar-test.js
- tests/integration/components/power-calendar/days-test.js
- tests/integration/components/power-calendar/nav-test.js
The reason is that the action takes a unit and a number, and displaces the center from
its current position that number of units.
However, I'm going to create another action that for convenience takes a single date/moment
and just sets the center to it.
> [BREAKING] Rename `changeCenter` to `moveCenter`

- CHANGELOG.md
- addon/components/power-calendar-range/days.js
- tests/dummy/app/styles/_base.scss
- tests/integration/components/power-calendar-range-test.js
If a day is both start and end of a range, it has the proper classes
> Fix classes of single-day ranges

- .travis.yml
- addon/components/power-calendar-multiple.js
- addon/components/power-calendar-range.js
- addon/components/power-calendar-range/days.js
- addon/components/power-calendar.js
- addon/components/power-calendar/days.js
- addon/templates/components/power-calendar.hbs
- app/styles/ember-power-calendar.scss
- config/ember-try.js
- package.json
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/public-pages/docs/range-selection.hbs
- tests/dummy/app/templates/snippets/range-selection-3.hbs
- tests/dummy/app/templates/snippets/range-selection-4.hbs
- tests/dummy/app/templates/snippets/range-selection-5.hbs
- tests/dummy/app/templates/snippets/range-selection-6.hbs
- tests/integration/components/power-calendar-range-test.js
Already working. Needs documentations before merging.
Example usage:
```hbs
{{#power-calendar minRange=3 as |cal|}} {{!-- Min range is three days --}}
{{#power-calendar minRange=0 as |cal|}} {{!-- Min range is 0 days, so the range can start and end on the same day --}}
{{#power-calendar minRange="48 hours" as |cal|}} {{!-- Range can be expressed as an humanized string --}}
{{#power-calendar minRange="1w" as |cal|}} {{!-- and can use abbreviations! --}}
```
> [FEATURE] Add `minRange` option

- CHANGELOG.md
- addon/components/power-calendar.js
- addon/components/power-calendar/days.js
- tests/integration/components/power-calendar/days-test.js
> Fix calendar when the `moment` global has a different locale

- addon/components/power-calendar/days.js
- tests/unit/components/power-calendar/days-test.js
I noticed that the id in the weeks array is always the first week of the month.
> Fix weeks id in days component

- CHANGELOG.md
- addon/components/power-calendar/days.js
- tests/integration/components/power-calendar-multiple-test.js
- tests/integration/components/power-calendar-test.js
The user can do that by passing `disabledDates=` to the {{cal.days}} component. Works both in single and multiple calendars, but not in range calendars because it’s clear to me what the right behaviour should be when a range contains a disabled calendar.
> [FEATURE] Allow to disable specific days

- package.json
- yarn.lock
Would it be possible to update ember-moment? 
The only breaking change with ember-moment (at [7.0.0](https://github.com/stefanpenner/ember-moment/blob/master/CHANGELOG.md#700)) was as follows:
> BREAKING: no longer defaults moment-format to LLLL and instead uses the moment default format (ISO 8601)
> Applications will need to specify the default format to LLLL if they want to keep this behavior: https://github.com/stefanpenner/ember-moment#global-default-output-format
Could that be a blocker? Tests look good.
> Bump ember-moment to 7.3.0

- tests/dummy/app/templates/snippets/datepicker-1.hbs
With the latest ember basic dropdown, the dropdown trigger is not properly called with trigger id. It miscalculates the position of the calendar which always appear at the top left of the window. Switching to `data-ebd-id` solves this problem.
> Fixes datepicker for new ember-basic-dropdown api

- tests/integration/components/power-calendar-multiple/days-test.js
- tests/integration/components/power-calendar/days-test.js
- tests/integration/components/power-calendar/nav-test.js
Still not async, but all tests use the new helpers
> Finish migration to native-dom-helpers

- tests/dummy/app/templates/snippets/the-nav-2.hbs
I changed `<button>` to `<button type="submit">` in the nav snippet. 
I found an old PR and realized why changing months refreshed my page. Should the docs include an explanation on why `type="submit"` might be needed?
> Set button type in nav snippet

- addon/components/power-calendar.js
- tests/integration/components/power-calendar-test.js
Hello,
your addons(ember-power-family) are great.
I experienced an issue while passing center with value null to power-datepicker. The result was a browser crash if moveCenter was called.
**Reason:**
moment(null) returns an invalid date, moment(undefined) returns the current-date.
With calling the CP instead of the center-property fixes the issue. Furthermore it turns out, that this change also fixes a test(92). 
What do you think about it?
> Fix issue experienced at ember-power-datepicker

- tests/integration/components/power-calendar-test.js
Hello,
if I visited http://localhost:4200/tests, the fixed test fails on Firefox. Obviously the focusin-event got not triggered, especially when dev-tools were open. I experienced the same issue at Chrome. 
Best regards
> Fix failing test, because of not triggered focusin-event in some browsers

- package.json
This addresses something I brought up as a tangent in #122. When I moved the dependency from `devDependencies` to `dependencies`, it [fixed](https://travis-ci.org/backspace/ember-power-calendar-import-bug/builds/306542225) it so I didn’t need to manually `ember install ember-native-dom-helpers`.
> Move DOM helper dependency

- addon/components/power-calendar-range.js
- tests/dummy/app/templates/public-pages/docs/range-selection.hbs
- tests/dummy/app/templates/snippets/range-selection-7.hbs
- tests/integration/components/power-calendar-range-test.js
So we've been using this awesome component at Uniplaces for almost a year. In the past few months we began to develop some improvements on our calendars, and this "proximity" feature was one of the most requested. Basically what we want to achieve with this is to select move dates based on the proximity of the chosen date.
For example, if you already selected the 1st of Jan as your start date and the 1st of March as your end date, if you now select the 5th of March it will only change the end date.
To accomplish this I've added a new flag to enable this behaviour.
You can check a demo here:
Would be super cool to have this reviewed/ merged if you think it's an useful feature. Thank you!
Documentation:
> [RFC] Select range by proximity feature

- CHANGELOG.md
- addon-test-support/index.js
- addon/components/power-calendar-multiple.js
- addon/components/power-calendar-multiple/days.js
- addon/components/power-calendar-range.js
- addon/components/power-calendar-range/days.js
- addon/components/power-calendar.js
- addon/components/power-calendar/days.js
- addon/helpers/power-calendar-format-date.js
- addon/services/power-calendar.js
- addon/utils/date-utils.js
- package.json
- tests/dummy/app/components/days-grid-without-mon-or-wed.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/controllers/public-pages.js
- tests/dummy/app/controllers/public-pages/docs/the-days.js
- tests/dummy/app/helpers/format-date.js
- tests/dummy/app/initializers/global-locale.js
- tests/dummy/app/templates/snippets/the-days-2-js.js
- tests/integration/components/power-calendar-multiple-test.js
- tests/unit/utils/date-utils-test.js
- yarn.lock
**Big change** 
This PR starts using the utility helpers from an external addon named `ember-power-calendar-moment`, which exposes those helpers as
`import { helper1, helper2... } from 'ember-power-calendar-utils';`
In the future this addon will not be a runtime dependency of ember-power-calendar, but an addon the user must install depending on the library they want to use (momentjs, date.js, luxon.js)
> Use moment meta addon

- addon/components/power-calendar/days.js
https://github.com/cibernox/ember-power-calendar/blob/6a2845426d3c0fb92eb38ceb58663d945ef5f45c/addon/components/power-calendar/days.js#L64-L65
For `locale="de"` `dayAbbr` is `'Mo.'`, while `weekdaysShort` contains `'Mo'`. This causes an infinite loop in `firstDay`:
https://github.com/cibernox/ember-power-calendar/blob/6a2845426d3c0fb92eb38ceb58663d945ef5f45c/addon/components/power-calendar/days.js#L228-L235
This PR does two things:
- prevent infinite loops by defaulting to index `0`
- use the full name instead of abbreviations to avoid inconsistencies
> fix(days): prevent infinite loop for first day

- addon-test-support/index.js
- tests/acceptance/helpers-test.js
- tests/dummy/app/templates/helpers-testing.hbs
- Replace 'getContext' with 'find'. It solves the issue when
a calendar is rendered inside a wormhole.
- Add example and test for this case to helpers test.
> Fix findCalendarElement

- addon/components/power-calendar-multiple.js
- tests/integration/components/power-calendar-multiple-test.js
- tests/integration/components/power-calendar-test.js
Allow multi select with `power-calendar-multiple` `actions.select` by passing in an array of dates.
Justification: #188
> Power Calendar Multiple Multi Select Action

- addon/components/power-calendar/nav.js
- addon/templates/components/power-calendar/nav.hbs
- tests/integration/components/power-calendar/nav-test.js
Doing a months component, adding the possibility to pass `unit` and `format` to the default nav would allow me to reuse it by passing `unit=year` and `format=YYYY`.
> make unit and format configurable in nav component

- addon/components/power-calendar-multiple.js
- addon/components/power-calendar-range.js
- tests/integration/components/power-calendar-range-test.js
Passing `calendar.actions.select({ start, end })` to the range select action will now skip the range selection logic and directly pass the range to the user provided handler.
> Allow Range Select to Handle Range Objects

- tests/dummy/app/templates/public-pages/addons/index.hbs
It's not common knowledge that addons need to go in dependencies, not devDependencies, when they are wrapped. This adds a pointer to help new addon authors.
> Docs - Add instructions about using power calendar in other addons

- app/styles/ember-power-calendar.less
- app/styles/ember-power-calendar.scss
Ensures `$nav-button-color—focus` can be accurately overridden (and can be overridden using css vars).
Although the duplicate of lighten is probably an oversight, the initial value is increased to 20% to ensure there is no visual change from this PR.
Closes #214
> Remove duplicate nav focus style lighten

- package.json
ember-concurrency@1.0 was just released and there are no breaking changes.
> Add ember-concurrency 1.0 to package.json

- CHANGELOG.md
Release note said:
> The yielded components are not capitalized (e.g. `<calendar.Nav>`).
Which is incorrect.
> Correct release note breaking change

- CHANGELOG.md
- addon/components/power-calendar.js
- addon/templates/components/power-calendar.hbs
- package.json
- tests/integration/components/power-calendar-test.js
- yarn.lock
Before the library the library updated to octane #221 users could overwrite the `{{power-calendar}}`'s outer `div` by passing `tagName` to the component as an argument.
This PR restores that behavior with an optional `@tag` argument.
> Added optional @tag argument to <PowerCalendar />

- package.json
- yarn.lock
This is just a simple bump to the polyfill addon.
`0.0.1` uses a very old version of polyfill that was updated and if you have another addon that has this updated polyfill, one of them wins and one of them can't find the polyfill to import. :/
> bump element-closest-polyfill

- package.json
- yarn.lock
Similar to https://github.com/cibernox/ember-basic-dropdown/pull/584
> Widen `ember-truth-helpers` dependency constraint to allow v3.x

- .travis.yml
- config/ember-try.js
- package.json
- yarn.lock
Adds `^2.0.0-rc.1` versioning constraint to the ember-concurrency dependency entry, and adds two test scenarios to test against either version
This will enable folks using `ember-power-calendar` to migrate to ember-concurrency v2 in their apps, while preserving support for folks not able to upgrade (e.g. those on older Ember versions, or in need of legacy browser support)
> Enable use with ember-concurrency v2

- package.json
- yarn.lock
Using current ember-power-select with ember-power-calendar does not display a calendar with ember-element-helper on 0.3.2 (see https://github.com/lan0/calendar-foo)
> Bump ember-element-helper to 0.5.0

- addon/templates/components/power-calendar.hbs
- addon/templates/components/power-calendar/days.hbs
- addon/templates/components/power-calendar/nav.hbs
Noticed these deprecation warnings in my ember startup:
```
DEPRECATION: `hasBlock` is deprecated. Use `has-block` instead. ('ember-power-calendar/templates/components/power-calendar/days.hbs' @ L22:C18)  [deprecation id: has-block-and-has-block-params] See https://emberjs.com/deprecations/v3.x#toc_has-block-and-has-block-params for more details.
```
> Replace hasBlock with has-block [deprecation id: has-block-and-has-block-params]

- addon/templates/components/power-calendar.hbs
- addon/templates/components/power-calendar/days.hbs
- addon/templates/components/power-calendar/nav.hbs
As of Ember 3.26, using `hasBlock` is deprecated. The non-deprecated version is to invoke `has-block` as a helper without params, so that's what I've migrated to!
It seems like `has-block` was introduced in Ember 3.10, so with 3.13 being the earliest version that this addon is tested against, it should be safe to release as a non-breaking change 🎉
> fix: resolve `hasBlock` usage deprecation

- addon/templates/components/power-calendar.hbs
- tests/dummy/app/templates/snippets/nav-select-1.hbs
- tests/dummy/app/templates/snippets/the-days-1.hbs
The `with` helper is deprecated. We should use `let` instead.
> Use let instead of with

- CHANGELOG.md
- addon/index.js
- addon/utils.js
- package-lock.json
- package.json
- tests/dummy/app/app.js
- tests/dummy/app/components/snippets/installation.js
- tests/dummy/app/templates/public-pages/docs/installation.hbs
> Add `registerDateLibrary` to allow register every date library & allow `ember-truth-helpers` v4

- ember-power-calendar/_index.scss
- ember-power-calendar/ember-power-calendar.scss
- ember-power-calendar/package.json
Add option for consumer apps to use import `@import 'ember-power-calendar.scss'`
this works with `ember-cli-scss` only by adding `scssOptions`
```js
let app = new EmberApp(defaults, {
...
sassOptions: {
includePaths: ['node_modules/ember-power-calendar'],
},
...
});
```
This was maybe working in older versions (without adding the setting `sassOptions`), but was not documented
> Add option to use `ember-power-calendar.scss`

- docs/app/templates/public-pages/docs/installation.hbs
- docs/ember-cli-build.js
- docs/package.json
- ember-power-calendar/babel.config.json
- ember-power-calendar/package.json
- pnpm-lock.yaml
- test-app/ember-cli-build.js
- test-app/package.json
* Update `ember-concurrency` to v4 (is now a V2 addon)
* Move `ember-concurrency` to peerDependencies -> consumer apps need to do manual steps to get work (see http://ember-concurrency.com/docs/installation -> Configure Babel Transform)
* Added notes for `ember-concurrency` installation in docs
> Update ember-concurrency to v4 and move to peerDependencies

- docs/app/app.ts
- docs/package.json
- pnpm-lock.yaml
- test-app/app/app.ts
- test-app/package.json
The finale step to remove the `@ts-expect-error` was to update `ember-power-calendar-moment` & `ember-power-calendar-luxon`
> Update ember-power-calendar-moment to v0.6.1

- ember-power-calendar/src/-private/days-utils.ts
Nowadays we rely on JavaScript dates when checking whether or not a day belongs to the same month. Which leads us to a problem, because depending on the timezone configured, we can jump or be behind by a day.
However, when using [momentjs.com/timezone/](https://momentjs.com/timezone/), it is necessary to rely on dateLibrary, to obtain the currentMonth instead of using the JavaScript date.
> Use datelibrary to compare months

- ember-power-calendar/package.json
- ember-power-calendar/src/components/power-calendar-multiple.hbs
- ember-power-calendar/src/components/power-calendar-multiple.ts
- ember-power-calendar/src/components/power-calendar-range.hbs
- ember-power-calendar/src/components/power-calendar-range.ts
- ember-power-calendar/src/components/power-calendar.hbs
- ember-power-calendar/src/components/power-calendar.ts
- pnpm-lock.yaml
This PR removes all usages from `@ember/render-modifiers`.
`@ember/render-modifiers` were meant as a transitional tool from the pre-Octane era, and not long-term usage.
See: https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-at-ember-render-modifiers.md
> Remove `@ember/render-modifiers`

- ember-power-calendar/less/base.less
- ember-power-calendar/scss/base.scss
While migrating from scss to css variables, we bumped into some issues with the ember power calendar mixin:
` codeFrame: Error: Undefined operation "calc(32px + var(--our-variable)) * 1".
╷
128 │       padding-left: $cell-with-spacing-width * 1;
│                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
/tmp/broccoli-474vURcC73g1RJ/out-944-funnel_funnel_styles/app/styles/ember-power-calendar.scss 128:21       ember-power-calendar()`
This code would make it possible to use css variables in the scss variables needed for the ember power calendar mixin.
> Add support for css variables to mixin

- ember-power-calendar/ember-power-calendar-for-css-generate.scss
- ember-power-calendar/rollup.config.mjs
While css variable introducing we have discovered that in generated css there was missing the css part which comes from mixin.
> Add missing mixin css part in generated css file (vanilla css)

- ember-power-calendar/ember-power-calendar-for-css-generate.scss
The scss to css convert brings for exaample:
```css
.ember-power-calendar .ember-power-calendar-day, .ember-power-calendar .ember-power-calendar-weekday {
max-width: "var(--ember-power-calendar-cell-size)";
max-height: "var(--ember-power-calendar-cell-size)";
width: "var(--ember-power-calendar-cell-size)";
height: "var(--ember-power-calendar-cell-size)";
}
```
Css variables aren't working in this case
After this fix the css variables are working:
```css
.ember-power-calendar .ember-power-calendar-day, .ember-power-calendar .ember-power-calendar-weekday {
max-width: var(--ember-power-calendar-cell-size);
max-height: var(--ember-power-calendar-cell-size);
width: var(--ember-power-calendar-cell-size);
height: var(--ember-power-calendar-cell-size);
}
```
> Fix css variable in vendor css

- ember-power-calendar/eslint.config.mjs
- ember-power-calendar/src/-private/utils.ts
- ember-power-calendar/src/components/power-calendar-multiple.ts
- ember-power-calendar/src/components/power-calendar-multiple/days.ts
- ember-power-calendar/src/components/power-calendar-range.ts
- ember-power-calendar/src/components/power-calendar-range/days.ts
- ember-power-calendar/src/components/power-calendar.ts
- ember-power-calendar/src/components/power-calendar/days.ts
- ember-power-calendar/src/test-support/helpers.ts
- ember-power-calendar/src/types/global.d.ts
After updating to ember 6.1 there was necessary to disable some eslint rules for typescript, as it follows not recommendedTypechecked with flat config.
This PR removes now finally all any usages inside the addon and we do also fix some incorrect typings.
We do ship this changes in v1 story (also when it is possible braking for consumers), because the typing were not correctly
> Improve typescript story

- ember-power-calendar/src/components/power-calendar-multiple.ts
- ember-power-calendar/src/components/power-calendar-range.ts
- ember-power-calendar/src/components/power-calendar.ts
- ember-power-calendar/src/test-support/helpers.ts
> Fix memory leak of `window.__powerCalendars` (remove hash when empty)

- ember-power-calendar/src/components/power-calendar-multiple.ts
- ember-power-calendar/src/components/power-calendar-range.ts
- ember-power-calendar/src/components/power-calendar.ts
While moving inside project to gts files i discoverd some glint issues (incorrect typings)
- locale is optional (by default it comes from service)
- yield paramter keys is incorrect
> Fix typing for glint

- ember-power-calendar/src/components/power-calendar-multiple.ts
- ember-power-calendar/src/components/power-calendar-multiple/days.ts
- ember-power-calendar/src/components/power-calendar-range.ts
- ember-power-calendar/src/components/power-calendar-range/days.ts
- ember-power-calendar/src/components/power-calendar.ts
- ember-power-calendar/src/components/power-calendar/nav.ts
In `ComponentLike` we need to pass the signature not the component.
> Fix `ComponentLike` (glint)

- ember-power-calendar/src/components/power-calendar-multiple.ts
- ember-power-calendar/src/components/power-calendar-range.ts
- ember-power-calendar/src/components/power-calendar.ts
Discovered in my app, that the `calendar` property is right now necessary from typing, but that incorrect, because we do add it internal and so you should never pass from outside
> Typing: Remove `calendar` from default blocks (not necessary to pass)

- ember-power-calendar/package.json
- ember-source: removed because the embroider / auto-import know what we intend - it's not bad to have if someone manages their dep graph correctly, which is easier with pnpm, but not everyone gets it right, and folks have a hard time tracking down errors
- @glimmer/tracking removed because it's a real package, but one we don't want to use. This comes up in embroider/vite where the presence of real packages always takes precedence over virtual packages. This is actually problematic because it can break reactivity in subtle ways, even if a dep graph is correct - allowing duplicates of dependencies, which for the glimmer internals, we don't want.
ref https://github.com/ember-cli/ember-addon-blueprint/pull/35
> Remove ember-source and glimmer tracking as a peer dependency
