package.json
same as https://github.com/cibernox/ember-power-select/pull/716
=> Depend on bugfree version of Ember-concurrency

tests/dummy/app/templates/public-pages/docs/action-handling.hbs
Not sure if "strictly" was what was intended here.
=> Fix typo: "extrictly" -> "strictly"

tests/dummy/app/templates/public-pages/docs/range-selection.hbs
This also makes it consistent with how it is written on the next page.
=> Add hyphen in "non-consecutive"

CHANGELOG.md, addon/components/power-calendar/days.js, addon/templates/components/power-calendar/days.hbs, app/styles/ember-power-calendar.scss, package.json, tests/assertions/is-day.js, tests/dummy/app/controllers/legacy-demo.js, tests/dummy/app/controllers/public-pages/docs/the-days.js, tests/dummy/app/templates/legacy-demo.hbs, tests/dummy/app/templates/public-pages/docs/the-days.hbs, tests/dummy/app/templates/snippets/the-days-6-js.js, tests/dummy/app/templates/snippets/the-days-6.hbs, tests/integration/components/power-calendar-test.js
This also refactors some internals and adds the first changelog
=> [FEATURE] Add `minDate` and `maxDate` to `{{calendar.days}}` component.

addon/components/power-calendar/days.js, addon/templates/components/power-calendar/days.hbs, tests/dummy/app/templates/public-pages/docs/the-days.hbs, tests/dummy/app/templates/snippets/the-days-7.hbs, tests/integration/components/power-calendar/days-test.js
=> [FEATURE] Allows different formats in the weekdays

CHANGELOG.md, addon/components/power-calendar-multiple.js, tests/dummy/app/templates/legacy-demo.hbs, tests/integration/components/power-calendar-multiple-test.js
=> [BUGFIX] Clicking on the last selected day selects it twice instead of removing it

package.json
Move `ember-assign-helper` from **devDependencies** to **dependencies**
=> Move ember-assign-helper

app/styles/ember-power-calendar.scss
Endeavors to address the issues present in #38.
* Provide less advanced fallback styling for button reset styles.
* Provide a flex-basis of 100% to somehow cajole IE11 to respect the max-width on the weekday and day elements.
=> IE11 styling improvements

tests/dummy/app/templates/public-pages/docs/index.hbs
This sentence read a bit rough, so this is my attempt to smooth it out 😀
=> Slight grammatical tweak

addon/components/power-calendar/days.js
i saw this in a recent PR and I thought it could get cleaned up
=> add guard clauses to dayIsDisabled

tests/dummy/app/templates/public-pages/cookbook/datepicker.hbs
Fixes some typos in the datepicker section of the cookbook.
=> Fix some typos

app/styles/ember-power-calendar.scss
https://github.com/cibernox/ember-power-calendar/issues/59
=> fixes issue #59

app/styles/ember-power-calendar.less, app/styles/ember-power-calendar.scss, tests/dummy/app/templates/public-pages/docs/installation.hbs, tests/dummy/app/templates/snippets/installation-2a.scss
=> Mixin colors

addon/components/power-calendar-range.js, addon/components/power-calendar/days.js, tests/dummy/app/components/days-grid-without-mon-or-wed.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/legacy-demo.js, tests/dummy/app/controllers/public-pages/docs/the-days.js, tests/dummy/app/templates/snippets/the-days-2-js.js
https://momentjs.com/guides/#/lib-concepts/internal-properties/
TL;DR `_d` is unreliable when using timezones.
=> Moves from moment()._d to moment().toDate()

addon/templates/components/power-calendar.hbs, tests/dummy/app/templates/public-pages/docs/how-to-use-it.hbs, tests/dummy/app/templates/snippets/how-to-use-it-5.hbs, tests/integration/components/power-calendar-test.js
=> Displays the nav and days if no block is passed

.gitignore, .travis.yml, README.md
1. lock yarn version, this bug sometimes still occur https://github.com/sass/node-sass/issues/1579
2. added IntellijIDEA files to gitignore
3. Added final new line to README.md, when editing it, b/c `.editorconfig` says so
4. Added Travis Badge
=> add idea files to gitignore, add travis badge, fix yarn version

addon/components/power-calendar/days.js, addon/utils/is-integer.js, tests/integration/components/power-calendar-test.js
disable days by days of the week
```
disabledDates = [1, 2, 7]
```
disable all Monday, Tuesday and Sunday
=> using integers as days of the week (1 to 7)

package.json, yarn.lock
=> Remove ember-cli-shims

tests/dummy/app/templates/public-pages/docs/test-helpers.hbs
Hey, thanks for all your work on this, I’m excited to have a use for it!
=> Fix documentation typo

index.js
I updated `index.js` based on suggestion mentioned here: https://github.com/cibernox/ember-power-calendar/issues/178#issuecomment-425959681
Fixes #178
=> Fix dependency check which is broken under yarn workspaces

addon/components/power-calendar/days.js, tests/dummy/app/controllers/public-pages/cookbook/multiple-months.js, tests/dummy/app/router.js, tests/dummy/app/styles/app.scss, tests/dummy/app/templates/public-pages/cookbook.hbs, tests/dummy/app/templates/public-pages/cookbook/multiple-months.hbs, tests/dummy/app/templates/public-pages/cookbook/nav-select.hbs, tests/dummy/app/templates/snippets/multiple-months-1-css.css, tests/dummy/app/templates/snippets/multiple-months-1-js.js, tests/dummy/app/templates/snippets/multiple-months-1.hbs, tests/dummy/app/templates/snippets/multiple-months-2-css.css, tests/dummy/app/templates/snippets/multiple-months-2-js.js, tests/dummy/app/templates/snippets/multiple-months-2.hbs, tests/integration/components/power-calendar/days-test.js
Wonderful library. 
This is essentially a rebased version of #125, except I added a page to the cookbook for rendering multiple calendars.
All credit to @scanieso for inspiration in #125 
I tried to use conversational language in the cookbook... Though I am not a smart man so you should probably re-write it in your style. 
closes #125 
closes #124
=> Add ability to render multiple months

package.json, yarn.lock
This should help us fixing some issues when using ember canary.
=> Upgrade ember-concurrency

tests/dummy/app/templates/public-pages/docs/installation.hbs
as mentioned in https://github.com/cibernox/ember-power-calendar/issues/197#issuecomment-485169608
=> docs: add link to date-fns adapter

tests/dummy/app/templates/public-pages/docs/installation.hbs
I think this better covers what I think the intended meaning is.
=> Fix wording

addon/services/power-calendar.js
=> added locale setter to eliminate deprecation warning when setting a computed property

tests/dummy/app/templates/public-pages/docs/test-helpers.hbs
Thanks for the great addons, btw!
=> Fix a typo in test helper docs

package.json, yarn.lock
Update ember-power-select and ember-basic-dropdown as well to avoid conflicts.
=> Update ember-assign-helper to 0.3.0

addon/templates/components/power-calendar/nav.hbs
`calendar` is an argument thus needs to be prefixed with `@`.
=> Add another missing `@`

docs/package.json, pnpm-lock.yaml, test-app/package.json
Reverts cibernox/ember-power-calendar#438
=> Revert "Bump stylelint from 16.2.1 to 16.3.0"

ember-power-calendar/src/test-support/helpers.ts
Fixes https://github.com/cibernox/ember-power-calendar/issues/465
=> Fix use of dataset API in findCalendarGuid test-helper

.github/workflows/ci.yml, .github/workflows/push-dist.yml, docs/package.json, ember-power-calendar/package.json, pnpm-lock.yaml, test-app/package.json
Reverts cibernox/ember-power-calendar#523
=> Revert "Allow `@ember/test-helpers` v4 as dependency"

package.json, pnpm-lock.yaml, test-app/package.json
There was asked in #534 if we are fastboot compatible.
We had no test against fastboot...
This PR adds fastboot for test-app so that we are sure that everything works fine inside a fastboot app
=> Add fastboot in test-app
